sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

before_script:
  - eval "$(chef shell-init bash)"
  - chef --version

script:
  - cookstyle --version
  - foodcritic --version
